[package]
name = "xinod"
description = "xinod daemon and xz command-line Intent Bar."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
xz-types.workspace = true
xz-core = { path = "../core" }
xz-cortex = { path = "../cortex" }
xz-genome = { path = "../genome" }
xz-boot = { path = "../boot" }
tokio.workspace = true
